name: medical_assistant
description: "Отметка услуг (Медсестра)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.9.2
  liquid_glass_ui_design: ^1.0.5
  flutter_glass_morphism: ^1.0.0
  liquid_glass_effect: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  mobile_scanner: ^3.5.7
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_lucide: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.8
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.1
  analyzer: ^6.4.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rendered_services_parametrs.json
    - assets/get_employee.json
    - assets/brands/base_theme/
    - assets/brands/base_theme/logo.png

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  output-dir: lib/generated

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/brands/base_theme/logo.png"